"""
some_changes.

Revision ID: 9dbeba8f0a32
Revises: b57387b460c5
Create Date: 2025-12-12 02:19:25.917762

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = "9dbeba8f0a32"
down_revision: str | Sequence[str] | None = "b57387b460c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users_profiles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default="1",
        existing_comment="Флаг активности пользователя",
        existing_nullable=False,
        schema=DB_SCHEMA,
    )
    op.alter_column(
        "users_profiles",
        "last_login",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_comment="Дата и время последнего входа пользователя",
        schema=DB_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users_profiles",
        "last_login",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_comment="Дата и время последнего входа пользователя",
        schema=DB_SCHEMA,
    )
    op.alter_column(
        "users_profiles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="Флаг активности пользователя",
        existing_nullable=False,
        schema=DB_SCHEMA,
    )
    # ### end Alembic commands ###
