"""
added users model.

Revision ID: 3b9ceeaf3252
Revises:
Create Date: 2025-12-14 04:28:33.343221

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = "3b9ceeaf3252"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_profiles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False, comment="Имя пользователя"),
        sa.Column(
            "last_name",
            sa.String(length=30),
            nullable=False,
            comment="Фамилия пользователя",
        ),
        sa.Column("birth_date", sa.Date(), nullable=False, comment="Дата рождения пользователя"),
        sa.Column(
            "sex",
            sa.Enum(
                "MALE",
                "FEMALE",
                name="sex_choices",
                schema=DB_SCHEMA,
                inherit_schema=True,
                length=10,
            ),
            nullable=False,
            comment="Пол пользователя",
        ),
        sa.Column(
            "email",
            sa.String(length=50),
            nullable=False,
            comment="Электронная почта пользователя",
        ),
        sa.Column("password", sa.String(), nullable=False, comment="Хэш пароля пользователя"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="1",
            nullable=False,
            comment="Флаг активности пользователя",
        ),
        sa.Column(
            "last_login",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время последнего входа пользователя",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время обновления записи",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время удаления записи",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="0",
            nullable=False,
            comment="Флаг удаления записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=DB_SCHEMA,
    )
    op.create_index(
        op.f(f"ix_{DB_SCHEMA}_users_profiles_email"),
        "users_profiles",
        ["email"],
        unique=True,
        schema=DB_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_{DB_SCHEMA}_users_profiles_email"),
        table_name="users_profiles",
        schema=DB_SCHEMA,
    )
    op.drop_table("users_profiles", schema=DB_SCHEMA)
    # ### end Alembic commands ###
