"""
added intent model.

Revision ID: ebc1f9d05f64
Revises: 3b9ceeaf3252
Create Date: 2025-12-14 10:32:56.952900

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = "ebc1f9d05f64"
down_revision: str | Sequence[str] | None = "3b9ceeaf3252"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="ID пользователя"),
        sa.Column("message", sa.String(), nullable=False, comment="Сообщение пользователя"),
        sa.Column("intents", sa.String(), nullable=False, comment="Выданный интент"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время обновления записи",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время удаления записи",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="0",
            nullable=False,
            comment="Флаг удаления записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{DB_SCHEMA}.users_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=DB_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests_history", schema=DB_SCHEMA)
    # ### end Alembic commands ###
