"""
add dl_intent_appeals table.

Revision ID: e3f17c8119b2
Revises: 4a1d5f8c2e11
Create Date: 2026-04-02 17:31:32.054590

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA, DB_TEST_SCHEMA



# revision identifiers, used by Alembic.
revision: str = 'e3f17c8119b2'
down_revision: str | Sequence[str] | None = '4a1d5f8c2e11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
